#!/usr/bin/env node
// Generated by scripts/build-adapter-runtime.mjs; do not edit.

// packages/context/src/hooks.mjs
import { existsSync, mkdirSync, readFileSync, renameSync, writeFileSync } from "node:fs";
import { createHash } from "node:crypto";
import { dirname, isAbsolute, join, parse, relative, resolve } from "node:path";
function inputText() {
  return readFileSync(0, "utf8");
}
function parseInput() {
  const text = inputText().trim();
  return text ? JSON.parse(text) : {};
}
function sessionId(input) {
  return String(input.session_id || input.sessionId || "default").replace(/[^a-zA-Z0-9._-]/g, "_");
}
function runtimeStatePath(root, id) {
  return join(root, ".dotdotgod", "context", "runtime", `${id}.json`);
}
function declaredProjectRoot(input) {
  const value = input.project_dir || process.env.CLAUDE_PROJECT_DIR;
  return typeof value === "string" && value.trim() ? resolve(value) : null;
}
function findExistingStateRoot(cwd, id) {
  let current = resolve(cwd);
  const filesystemRoot = parse(current).root;
  while (true) {
    if (existsSync(runtimeStatePath(current, id))) return current;
    if (current === filesystemRoot) return null;
    current = dirname(current);
  }
}
function resolveHookContext(input, event) {
  const id = sessionId(input);
  const declared = declaredProjectRoot(input);
  if (declared) return { root: declared, path: runtimeStatePath(declared, id) };
  if (typeof input.cwd !== "string" || !input.cwd.trim()) return null;
  const existing = findExistingStateRoot(input.cwd, id);
  if (existing) return { root: existing, path: runtimeStatePath(existing, id) };
  if (event !== "sessionstart") return null;
  const root = resolve(input.cwd);
  return { root, path: runtimeStatePath(root, id) };
}
function readState(path) {
  try {
    return JSON.parse(readFileSync(path, "utf8"));
  } catch {
    return { loadRequired: false, pending: {} };
  }
}
function writeState(path, state) {
  if (!path) return;
  mkdirSync(dirname(path), { recursive: true });
  const temp = `${path}.${process.pid}.tmp`;
  writeFileSync(temp, `${JSON.stringify(state, null, 2)}
`);
  renameSync(temp, path);
}
function fileHash(path) {
  try {
    return createHash("sha256").update(readFileSync(path)).digest("hex");
  } catch {
    return "missing";
  }
}
function isInsideRoot(root, path) {
  if (!root || typeof path !== "string") return false;
  const absolute = resolve(path);
  const rel = relative(root, absolute);
  return rel === "" || !rel.startsWith("..") && !isAbsolute(rel);
}
function normalizeProjectPath(root, path) {
  if (!root || typeof path !== "string" || !path.trim()) return null;
  const absolute = resolve(root, path);
  return isInsideRoot(root, absolute) ? absolute : null;
}
function prunePending(state, root) {
  const next = {};
  for (const [path, fingerprint] of Object.entries(state.pending || {})) {
    const absolute = normalizeProjectPath(root, path);
    if (absolute) next[absolute] = fingerprint;
  }
  state.pending = next;
}
function toolName(input) {
  return String(input.tool_name || input.toolName || "");
}
function toolInput(input) {
  return input.tool_input || input.toolInput || {};
}
function mcpTool(name, suffix) {
  return name === suffix || name.endsWith(`__${suffix}`) || name.endsWith(`_${suffix}`);
}
function deny(reason) {
  return { hookSpecificOutput: { hookEventName: "PreToolUse", permissionDecision: "deny", permissionDecisionReason: reason } };
}
function commandFrom(input) {
  const value = toolInput(input);
  return String(value.command || value.cmd || "");
}
function isSubstantive(name) {
  return /^(Bash|Shell|local_shell|shell|shell_command|exec_command|Edit|Write|apply_patch)$/i.test(name);
}
function isImpactGate(name, input) {
  if (!/^(Bash|Shell|local_shell|shell|shell_command|exec_command)$/i.test(name)) return false;
  return /(^|\s)(test|build|lint|verify|commit|push|publish|deploy)(\s|:|$)|\b(git\s+(commit|push)|npm\s+(test|publish)|pnpm\s+[^\n]*(test|build|lint|verify|publish))\b/i.test(commandFrom(input));
}
function changedPath(input, root) {
  const value = toolInput(input);
  const path = value.file_path || value.path;
  return normalizeProjectPath(root, path);
}
function hasFailedToolResult(input) {
  const response = input.tool_response || input.toolResponse || input.tool_result || input.toolResult || input.result;
  if (!response || typeof response !== "object") return false;
  if (response.is_error === true || response.isError === true || response.error) return true;
  if (response.ok === false || response.status === "error" || response.status === "failed") return true;
  return false;
}
function runHook(event) {
  const input = parseInput();
  const name = toolName(input);
  const context = resolveHookContext(input, event);
  const state = readState(context?.path);
  state.pending ||= {};
  if (context) {
    prunePending(state, context.root);
    writeState(context.path, state);
  }
  if (event === "sessionstart") {
    if (!context) return {};
    state.loadRequired = true;
    writeState(context.path, state);
    return { hookSpecificOutput: { hookEventName: "SessionStart", additionalContext: "Dotdotgod project memory has not been loaded for this session. Before substantive shell or write work, call dotdotgod_project_load once with a concise task-specific focus." } };
  }
  if (event === "pretooluse") {
    if (mcpTool(name, "dotdotgod_project_load") || mcpTool(name, "dotdotgod_project_impact")) return {};
    if (state.loadRequired && isSubstantive(name)) return deny("Project memory is required first. Call dotdotgod_project_load with the current project root and a concise task-specific focus, then retry this tool.");
    const pendingPaths = Object.keys(state.pending);
    if (pendingPaths.length && isImpactGate(name, input)) return deny(`Graph impact is pending. Call dotdotgod_project_impact with paths=${JSON.stringify(pendingPaths)} and then retry this tool.`);
    return {};
  }
  if (event === "posttooluse") {
    if (!context) return {};
    if (mcpTool(name, "dotdotgod_project_load")) state.loadRequired = false;
    else if (mcpTool(name, "dotdotgod_project_impact")) {
      const checked = toolInput(input).paths;
      let cleared = 0;
      if (Array.isArray(checked)) for (const path of checked) {
        const absolute = normalizeProjectPath(context.root, path);
        if (absolute && Object.hasOwn(state.pending, absolute)) {
          delete state.pending[absolute];
          cleared += 1;
        }
      }
      writeState(context.path, state);
      if (cleared > 0 && hasFailedToolResult(input)) return { hookSpecificOutput: { hookEventName: "PostToolUse", additionalContext: `dotdotgod_project_impact reported a failure, but dotdotgod cleared pending graph impact for ${cleared} requested path(s) to avoid a blocking retry loop. Review the impact error before broad operations.` } };
      return {};
    } else if (/^(Edit|Write|apply_patch)$/i.test(name)) {
      const path = changedPath(input, context.root);
      if (path) state.pending[path] = fileHash(path);
    }
    writeState(context.path, state);
    return {};
  }
  return {};
}
function hookMain(event) {
  try {
    process.stdout.write(`${JSON.stringify(runHook(event))}
`);
  } catch (error) {
    process.stderr.write(`dotdotgod hook error: ${error instanceof Error ? error.message : String(error)}
`);
    process.stdout.write("{}\n");
  }
}

// packages/codex/hooks/runtime-entry.mjs
hookMain(process.argv[2] || "");
