import { runInit } from './init.mjs';
import { commandUsage, hasHelpToken, helpCommandFromArgs, isHelpToken, isVersionToken, printVersion, usage } from './cli/usage.mjs';
import { runValidate } from './validate/run.mjs';
import { runIndex, runStatus } from './index/cache.mjs';
import { runConfig } from './commands/config.mjs';
import { runQuery } from './commands/query.mjs';
import { runMap } from './commands/map.mjs';
import { runResolve, runExpand } from './reference/resolve.mjs';
import { runTraceability } from './commands/traceability.mjs';
import { runGraph } from './commands/graph.mjs';

export { CACHE_VERSION } from './index/constants.mjs';
export { commandUsage, hasHelpToken, helpCommandFromArgs, isHelpToken, isVersionToken, parseCommon, printVersion, usage } from './cli/usage.mjs';
export { rel } from './common/paths.mjs';
export { extractAnchors, extractFirstHeading, extractLinks, headingToAnchor, isKebabCase, isNumberedSeriesFilename, isUpperSnakeMarkdown, removeCodeBlocks, suggestFilenameFromHeading } from './docs/markdown.mjs';
export { extractDotdotgodTraceabilityBlocks, findTraceabilityLinksRegion, isLocalRelativeTraceabilityPath, renderCompactTraceabilityBlock, stripTraceabilityLinksRegion, syncTraceabilityLinksInContent, traceabilityExample, validateTraceabilityBlock, validateTraceabilityLinksRegion, validateTraceabilityPlacement } from './docs/traceability.mjs';
export { DEFAULT_IMPACT_RANKING_POLICY, DEFAULT_LOAD_POLICY, DEFAULT_VALIDATION_POLICY, SEMANTIC_RELATIONS, cloneImpactRankingPolicy, cloneLoadPolicy, cloneReferenceExpansionPolicy, cloneValidationPolicy, defaultDotdotgodConfigData, defaultDotdotgodConfigText, defaultMemoryConfig, isValidDocumentationRoot, normalizeDocumentationRoot, isMarkdownSizeExcluded, isSecretLikePathPattern, isValidPathPattern, matchPathPattern, memoryAreaForPath, memoryConfigSummary, normalizeLowSignalTerm, readMemoryConfig, requiresTraceability, resolveMemoryArea, validateMemoryConfigData } from './memory/config.mjs';
export { BUILT_IN_TEMPLATE_NAMES, DEFAULT_TEMPLATE_NAME, builtInTemplateData, builtInTemplateScaffold, builtInTemplateText, dotdotgodHome, resolveInitializationTemplate } from './config/templates.mjs';
export { buildCommunities, relationWeight } from './graph/communities.mjs';
export { addEdge, addNode, compactGraph, expandGraph, graphStats, jsonSize, shardFile, writeJson } from './graph/store.mjs';
export { cacheFile, collectIndexFiles, fingerprint, shouldIndexPath } from './index/files.mjs';
export { buildMemoryAreas, detectCommandGuidance, detectPackageManager } from './memory/summary.mjs';
export { buildDocumentationMap, formatDocumentationTree } from './memory/documentation-map.mjs';
export { isReadmeIndexPath, retrievalMetadataForPath } from './graph/metadata.mjs';
export { buildGraph } from './graph/extract.mjs';
export { addDeterministicSemanticEdges } from './graph/semantic.mjs';
export { buildIndex, writeIndex, readIndex, getStatus, runIndex, runStatus, readFreshIndex, graphSummary } from './index/cache.mjs';
export { runValidate } from './validate/run.mjs';
export { buildImpactReport, buildCompactImpactReport } from './impact/report.mjs';
export { buildChangedFileProfile, MAX_VECTOR_PROFILE_CHARS, MAX_VECTOR_PROFILE_FILE_BYTES, MAX_VECTOR_PROFILE_METADATA_ITEMS } from './impact/vector-profile.mjs';
export { buildVectorImpactOverlay, VECTOR_RELATION_WEIGHT } from './impact/vector-overlay.mjs';
export { formatCompactImpactOutput, formatYmlGraphImpactError, formatYmlImpactOutput } from './impact/format.mjs';
export { runConfig } from './commands/config.mjs';
export { runMap } from './commands/map.mjs';
export { buildVectorIndex, cosineScore, parseQueryOptions, queryDocumentation, rankVectorFiles, runQuery } from './commands/query.mjs';
export { chunkMarkdown, collectDocumentationChunks, collectDocumentationMarkdown, textFingerprint } from './query/chunks.mjs';
export { readVectorCache, VECTOR_DIMENSIONS, VECTOR_MODEL, VECTOR_SCHEMA_VERSION, profileFingerprint, vectorCachePaths, writeVectorCache } from './query/store.mjs';
export { DEFAULT_EMBEDDING_PROFILE, EMBEDDING_PROVIDERS, embeddingProfileIdentity, resolveEmbeddingProfile, sanitizeEmbeddingProfile, validateEmbeddingProfile } from './query/embedding-config.mjs';
export { createEmbedder, resolveEmbedder } from './query/embedder.mjs';
export { extractBracketReferences, extractFuzzyReferences, normalizeReferenceAlias } from './reference/extract.mjs';
export { resolveReferenceCandidates, runResolve, runExpand } from './reference/resolve.mjs';
export { parseTraceabilityOptions, runTraceability } from './commands/traceability.mjs';
export { parseGraphOptions, runGraph } from './commands/graph.mjs';

export async function runCli(argv = process.argv.slice(2)) {
  const [command = 'help', ...args] = argv;
  if (isVersionToken(command)) printVersion();
  if (command === 'help') usage('', helpCommandFromArgs(args));
  if (isHelpToken(command)) usage('');
  if (hasHelpToken(args)) usage('', helpCommandFromArgs([command, ...args]));
  if (command === 'validate') runValidate(args);
  else if (command === 'init') runInit(args, usage);
  else if (command === 'index') runIndex(args);
  else if (command === 'config') runConfig(args);
  else if (command === 'status') runStatus(args);
  else if (command === 'query') await runQuery(args);
  else if (command === 'map') runMap(args);
  else if (command === 'resolve') runResolve(args);
  else if (command === 'expand') runExpand(args);
  else if (command === 'traceability') runTraceability(args);
  else if (command === 'graph') await runGraph(args);
  else usage(`Unknown command: ${command}`);
}
